### ISSUE TITLE
English version of docs?

### ISSUE THREAD

**Issue by medakk** [michael-lehn/ulmBLAS#5]
Is there possible an english version of https://apfel.mathematik.uni-ulm.de/~lehn/sghpc/index.html ?

**Comment by michael-lehn** [comment]
Hi Karthik,

you can have a look at the website that I used last year for the exercises:

http://www.mathematik.uni-ulm.de/numerik/hpc/ss19/session12/page01.html <http://www.mathematik.uni-ulm.de/numerik/hpc/ss19/session12/page01.html>

However, most of the content you see there is based on what was discussed in the lectures. It’s just short summary of the essentials that were needed for the exercises.

Best regards,
Michael

P.S.: This is the link to the course I am doing this semester

	http://www.mathematik.uni-ulm.de/numerik/hpc/ss20/hpc0/index.html <http://www.mathematik.uni-ulm.de/numerik/hpc/ss20/hpc0/index.html>

But I reorganised the overall structure of the lecture. We now begin with logic gates for building an ALU, then use a virtual computer to learn programming first with machine code, then assembly, then C etc. So it will take some time before we come to the topics you seem to be interested in …

**Comment by medakk** [comment]
That helps so much! Thanks a lot!

**Comment by medakk** [comment]
The links you shared seem to be down.

**Comment by michael-lehn** [comment]
Due to necessary repairs in the math department the electric power supply for the building complex needed to be shutdown…. And this includes our servers.

**Comment by medakk** [comment]
Could you please upload the assignment description on these pages? I do not have access to Moodle

**Comment by michael-lehn** [comment]
Could you sent me links to pages where the assignment description is not sufficient?

On Moodle there is actually not much more information, basically just links to the relevant pages. But I am interested in making the pages a self-contained as possible. This certainly will be an iterative process due to time constraints. At the moment I compensate shortcomings with regular video conferences. Having feedback from an outsider might be an important input for how to choose the priority for updating the websites ...

**Comment by medakk** [comment]
In this page: http://www.mathematik.uni-ulm.de/numerik/hpc/ss20/hpc0/session03/page04.html

Its my fault though, I had skipped the video. Its quite obvious what the assignment is now.

**Comment by michael-lehn** [comment]
> On 29. Jun 2020, at 16:10, Karthik Karanth <notifications@github.com> wrote:
> 
> 
> In this page: http://www.mathematik.uni-ulm.de/numerik/hpc/ss20/hpc0/session03/page04.html <http://www.mathematik.uni-ulm.de/numerik/hpc/ss20/hpc0/session03/page04.html>
> Its my fault though, I had skipped the video. Its quite obvious what the assignment is now.
> 
Yes, it was just about breaking the ice when the semester started. Just to get some feedback:

**Comment by medakk** [comment]
Hello,

How do I obtain the ulm assembler(and tools)? I found https://github.com/michael-lehn/ulm but I don't know how to build it.

**Comment by michael-lehn** [comment]
Hi Karthik
> How do I obtain the ulm assembler(and tools)? I found https://github.com/michael-lehn/ulm <https://github.com/michael-lehn/ulm> but I don't know how to build it.
> 
that is an ancient version of the ULM and I simply forgot to delete it. Currently we use a local git repository until we have a stage that can face public. I have attached a snapshot of the current state. It contains the following:

- the command line tool: ulm
- the debugger: ulm-qui (requires Qt5)
- the assembler: ulmas
- the linker: ulmld (and creating static libraries: ulmranlib)
- the compiler for a subset of C: ulmcc

I didn’t have the time so far to make to easy-to-build. So expect some obstacles …

Ideally you just would change into ulm-tools and build and install (to /usr/local) everything with

	make depend install

or for example with

	make PREFIX=$HOME/ulm BINDIR=$HOME/bin depend install

in the home directory.

However, at the moment that does not call the Makefile for ulm-qui. So try that manually:

	cd ulm-tools/ulmqui
	qmake
        make
	
I really should have written up a list of requirements: Certainly decent versions of g++, bison, gmblib and boost.

Let me know if it compiles!

Best regards,
Michael

**Comment by medakk** [comment]
I don't think attachments work with GitHub comment replies. Could you email it(my email is listed on my [github profile](https://github.com/medakk)) or upload it elsewhere?
