### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by miguelraz** [michael-lehn/ulmBLAS#6]
Professor Lehn, I'm sorry to say that the links to apfel.mathematik.uni-ulm.de/~lehn/sghpc/gemm/index.html and the rest of the course seem to be down - the Software Grundlagen für HPC is a highly useful resource, and not all pages are available with the WayBack Machine.

It would be a shame if they can't be recovered.
I also understand that it can be sometimes accessed with the http only link http://apfel.mathematik.uni-ulm.de/~lehn/sghpc/gemm/index.html but the stables Firefox/Chrome versions today doesn't like it either :/.

Thanks for your effort in putting together this course anyways!

**Comment by michael-lehn** [comment]
Thanks for telling me. We stopped actively using the machine which is hosting the website a long time ago. I will check if there is a serious problem with the server. In the worst case I will host the website on a new server.

**Comment by miguelraz** [comment]
Wie sc&ön! Vielen Dank!

**Comment by miguelraz** [comment]
Beautiful! The website's up!
Will close.
